k0sproject/bootloose

pkg/cluster/cluster.go
pkg/docker/info.go

Add support for cgroupv2 so it works with Docker Desktop 4.3 and newer.
Fixes https://github.com/weaveworks/footloose/issues/270

Add support for cgroupv2

---

pkg/cluster/run.go

Some tiny distros like Alpine, does not include bash by default. Use /bin/sh which is specified by POSIX.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html

ssh: use POSIX shell /bin/sh to copy files

---

images/debian10/Dockerfile

My left-open PR 282 from old repo recreated
Clears the machine ID files to force regeneration on Debian 10. Previously the image had a pre-set constant machine ID on all instances which didn't make kube happy on multi node clusters.
Commands replicated from Dockerfiles for other images, such as https://github.com/k0sproject/footloose/blob/main/images/ubuntu20.04/Dockerfile#L20-L21

Make machine IDs unique on Debian 10

---

pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/key_store.go
pkg/config/cluster.go
pkg/docker/archive.go
tests/e2e_test.go

Replaces ioutil usages with the modern alternatives.
Includes some gofmt created import reordering on the modified files.

Drop deprecated ioutil

---

pkg/docker/info.go

Not sure why this doesn't affect go.mod/go.sum 🤔

Fix pkg/exec import to point to k0sproject/footloose

---

pkg/cluster/cluster.go
tests/test-create-delete-%image.cmd
tests/test-create-delete-persistent-%image.cmd
tests/test-create-stop-start-%image.cmd

Replaces the labels as suggested in https://docs.docker.com/config/labels-custom-metadata/#key-format-recommendations

Rename container labels to io.k0sproject.footloose

---

go.mod
go.sum
pkg/cluster/formatter.go
pkg/config/get.go
pkg/docker/info.go

- pkg/config/get.go:19:15: SA1019: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
- pkg/docker/info.go:29:3: S1025: the argument is already a string, there's no need to use fmt.Sprintf (gosimple)
- pkg/cluster/formatter.go:96:2: SA4005: ineffective assignment to field writer.err (staticcheck)

Fix linting errors 

---

images/fedora38/Dockerfile
tests/variables.json

The Dockerfile is so spartan that I suspect it may not be fully footloosified.

Bump fedora image from version 29 to 38

---

tests/test-basic-commands-%image.cmd
tests/test-config-get-ubuntu18.04.cmd
tests/test-create-config-already-exists-%image.cmd
tests/test-create-delete-%image.cmd
tests/test-create-delete-idempotent-%image.cmd
tests/test-create-delete-persistent-%image.cmd
tests/test-create-stop-start-%image.cmd
tests/test-show-ubuntu18.04.cmd
tests/test-ssh-remote-command-%image.cmd
tests/test-ssh-user-%image.cmd
tests/test-start-stop-specific-%image.cmd

The e2e tests generate config and key files that are left behind when the tests finish, cluttering the tests/ dir with untracked files.

Cleanup of leftover files generated during e2e tests

---

.github/workflows/go.yml
tests/Makefile
tests/test-docker-in-docker-debian10.cmd

Fix failing debian10 docker-in-docker e2e test

---

.github/workflows/go.yml
tests/Makefile
tests/e2e_test.go

Instead of requiring and using `footloose` in PATH, replaces the `footloose` commands encountered in e2e `.cmd` files with `go run <project_root>/.`. This allows modifying code and running tests without installing a development version into PATH.

Replace "footloose" with "go run ...." in e2e tests

---

README.md

Readme had an old `go get` install example that doesn't work on modern go versions. 
TODO: This one doesn't work either since there is no `@latest`.

Change "go get" to "go install" in README.md

---

images/alpine3.18/Dockerfile
images/amazonlinux2/Dockerfile
images/amazonlinux2023/Dockerfile
images/clearlinux/Dockerfile
images/fedora38/Dockerfile
tests/test-unique-machine-id-%image.cmd

* Adds a test for checking if the machines get unique machine ids. K8s and some others do not like it when nodes have non-unique machine ids.
* Fixes the images where this was broken

Ensure that each machine gets a unique machine-id

---

pkg/cluster/cluster.go

Set --cgroup-parent bootloose.slice fo cgroupv2. This appears to fix issue when running bootloose on Alpine Linux.
Fixes #55

Set the parent cgroup for docker

---

go.mod
go.sum
pkg/cluster/cluster.go

That function is actually that small that it can be embedded here. The homedir module is no longer actively maintained. Moreover, there were some places in the bootloose code which didn't check properly for errors, potentially continuing using an empty path.

Inline homedir.Expand and remove dependency

---

.github/workflows/check-copyright-boilerplate.yaml

Otherwise, the script can't detect the right copyright years.
Also narrow down the GitHub token's privileges.

Check out full history when checking copyrights

---

.github/workflows/publish-images.yaml

The previous solution required a full checkout of the repo in order to determine which images had changed. There was a subtle bug in there, as the checkout was not done with full depth. Only the most recent commit was fetched. This led to situations where the image list generation failed with "bad object" errors.
There's a more straightforward approach using the GitHub API and the gh CLI. It allows for easy fetching of diffs and massaging them via jq queries. The same can be done to get the file list of a repository, eliminating the need for a checkout in both cases.

Use GitHub API to list images

---

.github/workflows/publish-image.yaml
.github/workflows/publish-images.yaml

Factor out the matrix build in its own workflow. Allow for the workflow to be triggered manually. This allows individual images to be published manually.

Separate publish-image workflow

---

.github/workflows/publish-images.yaml

This unlocks the gh CLI usage.

Add GH_TOKEN to workflow step

---

pkg/cluster/cluster.go
pkg/config/machine.go

Adds `extraArgs` config option for machines.
This allows us to enable ipv6 for a machine by setting `extraArgs: [--sysctl net.ipv6.conf.all.disable_ipv6=0]`.

Add config option for docker extra args

---

.github/workflows/publish-images.yaml

This unlocks the gh CLI usage.

Add GH_REPO to workflow step

---

pkg/cluster/cluster.go

Since Docker 25, read-only mounts will be recursively read-only. That spoils the fun for systemd.

Don't mount cgroups read-only for cgroups V1

---

cmd/bootloose/config_create.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/config/cluster.go
pkg/config/get_test.go

Adds a `--volume|-v` flag to `bootloose config create`. The syntax of the value is the same as in docker cli (`-v /tmp:/run:rw`). Like `--privileged`, the flag applies to all machines that are added to the config.

Add a --volume/-v config create option
